// Do not edit this file!
// This file may only be edited by Engima's ASCOM Editor!
//
// <ASCOM version="1">
// <Prefix>opp</Prefix>
// <Functions>
// <Function Name="SideChat" Params="text" Ret="false" A="true" C="false" S="false" O="false" OC="false" P="false" />
// <Function Name="sideChatGroup" Params="text, group" Ret="false" A="true" C="false" S="false" O="false" OC="false" P="false" />
// </Functions>
// </ASCOM>

ASCOM_ClientID = 0;
ASCOM_CallID = 0;
ASCOM_LastCallID = 0;
ASCOM_LockCallID = 0;

"oppSideChatEventArgs" addPublicVariableEventHandler {
    private ["_array"];

    _array = _this select 1;

    _array spawn {
        if ((_this select 0 == "A") || (_this select 0 == "C" && !isDedicated)) then {
            (_this select 1) call oppSideChat;
        };
    };
};

oppSideChatAll = {
    if (isNil "_this") then { _this = []; };
    oppSideChatEventArgs = ["A", _this];
    publicVariable "oppSideChatEventArgs";
    _this call oppSideChat;
    oppSideChatEventArgs = [];
};


"oppsideChatGroupEventArgs" addPublicVariableEventHandler {
    private ["_array"];

    _array = _this select 1;

    _array spawn {
        if ((_this select 0 == "A") || (_this select 0 == "C" && !isDedicated)) then {
            (_this select 1) call oppsideChatGroup;
        };
    };
};

oppsideChatGroupAll = {
    if (isNil "_this") then { _this = []; };
    oppsideChatGroupEventArgs = ["A", _this];
    publicVariable "oppsideChatGroupEventArgs";
    _this call oppsideChatGroup;
    oppsideChatGroupEventArgs = [];
};



if (isServer) then {
    "ASCOM_AskForClientID" addPublicVariableEventHandler {
        private ["_unit"];

        _unit = _this select 1;
        ASCOM_AskForClientID = [];
        ASCOM_LastCallID = ASCOM_LastCallID + 1;
        ASCOM_ClientIDResponse = [_unit, ASCOM_LastCallID];
        publicVariable "ASCOM_ClientIDResponse";
    };

    ASCOM_ServerInitialized = true;
    publicVariable "ASCOM_ServerInitialized";
    ASCOM_Initialized = true;
}
else {
    "ASCOM_ClientIDResponse" addPublicVariableEventHandler {
        private ["_array"];

        _array = _this select 1;
        ASCOM_ClientIDResponse = [];

        if (player == (_array select 0)) then {
            ASCOM_ClientID = _array select 1;
            ASCOM_Initialized = true;
        };
    };

    waitUntil {!isNull player};
    ASCOM_AskForClientID = player;
    publicVariable "ASCOM_AskForClientID";
};
